name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-state: '3.9'
        
    - name: Install dependencies
      run: |
        cd services/task-api
        pip install -r requirements.txt
        
    - name: Terraform Lint
      uses: hashicorp/setup-terraform@v2
    - run: |
        cd terraform
        terraform init -backend=false
        terraform validate
        
    - name: Build Docker Image
      run: |
        docker build -t task-api ./services/task-api
